// Generated by jproto

import Foundation

struct User: Codable {
	let id: Int 
	let rate: Float 
	let rateOptional: Float? 
	let name: String? 
	let isActive: Bool 
	let friends: [User] 
	let child: User 

	enum CodingKeys: String, CodingKey {
		case id = "id"
		case rate = "rate"
		case rateOptional = "rate_optional"
		case name = "name"
		case isActive = "is_active"
		case friends = "friends"
		case child = "child"
	}
}